friends/config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :friends
  root 'friends#index'
end

friends/app/models/friend.rb
class Friend < ApplicationRecord
  belongs_to :user
end

friends/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
        :recoverable, :rememberable, :validatable
  has_many :friends
end

friends/app/controllers/friends_controller.rb
class FriendsController < ApplicationController
  before_action :set_friend, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, except: [:index, :show]
  before_action :correct_user, only: [:edit, :update, :destroy]

  # GET /friends or /friends.json
  def index
    @friends = Friend.all
  end

  # GET /friends/1 or /friends/1.json
  def show
  end

  # GET /friends/new
  def new
    @friend = current_user.friends.build
  end

  # GET /friends/1/edit
  def edit
  end

  # POST /friends or /friends.json
  def create
    @friend = current_user.friends.build(friend_params)
    respond_to do |format|
      if @friend.save
        format.html { redirect_to friends_url, notice: "Friend was successfully created." }
        format.json { render :show, status: :created, location: @friend }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @friend.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /friends/1 or /friends/1.json
  def update
    respond_to do |format|
      if @friend.update(friend_params)
        format.html { redirect_to friends_url, notice: "Friend was successfully updated." }
        format.json { render :show, status: :ok, location: @friend }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @friend.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /friends/1 or /friends/1.json
  def destroy
    @friend.destroy

    respond_to do |format|
      format.html { redirect_to friends_url, notice: "Friend was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def correct_user
    @friend = current_user.friends.find_by(id: params[:id])
    redirect_to friends_path, notice: "Not Authorized To Edit / Destroy This Friend" if @friend.nil?
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_friend
      @friend = Friend.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def friend_params
      params.require(:friend).permit(:name, :email, :user_id)
    end
end

friends/app/helpers/friends_helper.rb
module FriendsHelper
end

friends/app/views/friends/_form.html.erb
<%= form_with(model: friend) do |form| %>
  <% if friend.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(friend.errors.count, "error") %> prohibited this friend from being saved:</h2>

      <ul>
        <% friend.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="mb-3">
    <%= form.text_field :name, class: "form-control", placeholder: "Name..."  %>
  </div>

  <div class="mb-3">
    <%= form.text_field :email, class: "form-control", placeholder: "Email..."  %>
  </div>

  <div class="mb-3">
    <%= form.number_field :user_id, id: :friend_user_id, class: "form-control", placeholder: "User Id...", value: current_user.id, type: :hidden  %>
  </div>

  <div class="mt-4">
    <%= form.submit "Submit", class: "btn btn-primary" %>
  </div>
<% end %>

friends/app/views/friends/_friend.html.erb
<div id="<%= dom_id friend %>">
  <p>
    <strong>Name:</strong>
    <%= friend.name %>
  </p>

  <p>
    <strong>Email:</strong>
    <%= friend.email %>
  </p>

</div>

friends/app/views/friends/edit.html.erb
<h1>Editing friend</h1>

<%= render "form", friend: @friend %>

<br>

<div class="d-flex">
  <%= button_to "Show", @friend, method: :get, class: "btn btn-info" %>
  <%= button_to "Back", friends_path , method: :get, class: "btn btn-dark mx-3"%>
</div>

friends/app/views/friends/index.html.erb
<% if user_signed_in? %>
<table class="table table-bordered table-hover">
  <thead class="table-dark">
    <tr>
      <th scope="col">Name</th>
      <th scope="col">Email</th>
      <th scope="col">User Id</th>
      <th scope="col"></th>
    </tr>
  </thead>
  <tbody>
    <% @friends.each do |friend| %>
      <% if friend.user == current_user%>
        <tr>
          <td>
            <%= link_to friend.name, friend, method: :get %>
          </td>
          <td><%=friend.email%></td>
          <td><%=friend.user_id%></td>
          <td>
            <%= button_to "Destroy", friend, method: :delete, class: "btn btn-outline-danger" %>
          </td>
        </tr>
      <%end%>
    <% end %>
  </tbody>
</table>
<%else%>
  <h1>Hello World!</h1>
  This is my Rails social network.
<%end%>

friends/app/views/friends/new.html.erb
<h1>Add New friend</h1>

<%= render "form", friend: @friend %>

<br>

<div>
  <%= button_to "Back", friends_path , method: :get, class: "btn btn-dark"%>
</div>

friends/app/views/friends/show.html.erb
<div class="card mb-3">
  <div class="card-body">
    <%= render @friend %>
    <div class="d-flex">
      <%= button_to "Edit", edit_friend_path(@friend) , method: :get, class: "btn btn-warning"%>
      <%= button_to "Back", friends_path , method: :get, class: "btn btn-dark mx-3"%>
    </div>
  </div>
</div>

friends/app/views/layouts/_flash.html.erb
<% flash.each do |message_type, message|%>
  <div class="alert <%= message_type == "notice" ? "alert-info" : "alert-warning" %> alert-dismissible fade show" role="alert">
    <%= message %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
  </div>
<%end%>

friends/app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark mb-3">
  <div class="container-fluid">
    <a class="navbar-brand" href="<%= root_path%>">FriendsApp</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link" aria-current="page" href="<%= root_path%>">Friends</a>
        </li>

        <% if user_signed_in? %>
          <li class="nav-item">
            <a class="nav-link" aria-current="page" href="<%= new_friend_path%>">Add Friend</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" aria-current="page" href="<%= edit_user_registration_path%>">Edit Profile</a>
          </li>
          <li class="nav-item">
            <%= link_to "Logout", destroy_user_session_path, data: { "turbo-method": :delete } , class: "nav-link"%>
          </li>
        <%else%>
          <li class="nav-item">
            <a class="nav-link" aria-current="page" href="<%= new_user_session_path%>">Login</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" aria-current="page" href="<%= new_user_registration_path%>">Register</a>
          </li>
        <%end%>
      </ul>
    </div>
  </div>
</nav>

friends/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Friends App</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-iYQeCzEYFbKjA/T2uDLTpkwGzCiq6soy8tYaI1GyVh/UjpbCx/TYkiZhlZB6+fzT" crossorigin="anonymous">
  </head>

  <body>
    <%= render 'layouts/navbar'%>
    <div class="container">
      <%= render "layouts/flash"%>
      <%= yield %>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-u1OknCvxWvY5kfmNBILK2hRnQC3Pr17a+RTT6rIHI7NnikvbZlHgTPOOmMi466C8" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js" integrity="sha384-oBqDVmMz9ATKxIep9tiCxS/Z9fNfEXiDAYTujMAeBAsjFuCZSmKbSSUnQlmh/jp3" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/js/bootstrap.min.js" integrity="sha384-7VPbUDkoPSGFnVtYi0QogXtr74QeVeeIs99Qfg5YCF+TidwNdjvaKZX19NZ/e6oz" crossorigin="anonymous"></script>
  </body>
</html>